### Logistic Regression on Bank Marketing data

For the Bank Marketing data set available in <strong>Exercises/data </strong>folder, build a model using logistic regression model to predict the attribute “y” (i.e. the client will subscribe a term deposit or not) based on duration, age, and campaign as predictors.
<br/>Use 70% of the data as training data set and 30% of data as testing data set. 
<br/>Determine the classification accuracy rate of the model on both train and test set.
<br/><b>bank_marketing.csv</b> file contains the data and it's description is available in <b>bank_marketing.text</b> file.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [6]:
bank = pd.read_csv("data/bank_marketing.csv",delimiter=";")

In [8]:
bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
age               41188 non-null int64
job               41188 non-null object
marital           41188 non-null object
education         41188 non-null object
default           41188 non-null object
housing           41188 non-null object
loan              41188 non-null object
contact           41188 non-null object
month             41188 non-null object
day_of_week       41188 non-null object
duration          41188 non-null int64
campaign          41188 non-null int64
pdays             41188 non-null int64
previous          41188 non-null int64
poutcome          41188 non-null object
emp.var.rate      41188 non-null float64
cons.price.idx    41188 non-null float64
cons.conf.idx     41188 non-null float64
euribor3m         41188 non-null float64
nr.employed       41188 non-null float64
y                 41188 non-null object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [10]:
X = bank[["duration","age","campaign"]]
y = bank["y"]

In [11]:
bank["duration"]

0         261
1         149
2         226
3         151
4         307
5         198
6         139
7         217
8         380
9          50
10         55
11        222
12        137
13        293
14        146
15        174
16        312
17        440
18        353
19        195
20         38
21        262
22        342
23        181
24        172
25         99
26         93
27        233
28        255
29        362
         ...
41158     363
41159     514
41160     843
41161     510
41162     347
41163     385
41164    1868
41165     403
41166     651
41167     236
41168     144
41169     154
41170     293
41171     112
41172     353
41173     329
41174     208
41175     180
41176     360
41177     124
41178     483
41179     151
41180     254
41181     281
41182     112
41183     334
41184     383
41185     189
41186     442
41187     239
Name: duration, Length: 41188, dtype: int64

In [16]:
bank.groupby("campaign").count()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
campaign,,,,,,,,,,,,,,,,,,,,
1,17642,17642,17642,17642,17642,17642,17642,17642,17642,17642,17642,17642,17642,17642,17642,17642,17642,17642,17642,17642
2,10570,10570,10570,10570,10570,10570,10570,10570,10570,10570,10570,10570,10570,10570,10570,10570,10570,10570,10570,10570
3,5341,5341,5341,5341,5341,5341,5341,5341,5341,5341,5341,5341,5341,5341,5341,5341,5341,5341,5341,5341
4,2651,2651,2651,2651,2651,2651,2651,2651,2651,2651,2651,2651,2651,2651,2651,2651,2651,2651,2651,2651
5,1599,1599,1599,1599,1599,1599,1599,1599,1599,1599,1599,1599,1599,1599,1599,1599,1599,1599,1599,1599
6,979,979,979,979,979,979,979,979,979,979,979,979,979,979,979,979,979,979,979,979
7,629,629,629,629,629,629,629,629,629,629,629,629,629,629,629,629,629,629,629,629
8,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400,400
9,283,283,283,283,283,283,283,283,283,283,283,283,283,283,283,283,283,283,283,283
10,225,225,225,225,225,225,225,225,225,225,225,225,225,225,225,225,225,225,225,225
11,177,177,177,177,177,177,177,177,177,177,177,177,177,177,177,177,177,177,177,177
12,125,125,125,125,125,125,125,125,125,125,125,125,125,125,125,125,125,125,125,125
13,92,92,92,92,92,92,92,92,92,92,92,92,92,92,92,92,92,92,92,92
14,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69
15,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51
16,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51
17,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58
18,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33
19,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26
20,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30
21,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24
22,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
23,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
24,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15
25,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
26,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
27,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11
28,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
29,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
30,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
31,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
32,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
33,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
34,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
35,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
37,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
39,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
40,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
41,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
42,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
43,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
56,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [19]:
model = LogisticRegression()

In [20]:
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=100)

In [22]:
ytrain.shape

(28831,)

In [23]:
model.fit(xtrain,ytrain)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [25]:
model.score(xtrain,ytrain)

0.8924421629496029

In [29]:
ypredtest = model.predict(xtest)
ypredtrain = model.predict(xtrain)

In [36]:
confusiontest=confusion_matrix(ytest,ypredtest)
confusiontrain=confusion_matrix(ytrain,ypredtrain)

In [32]:
print(confusiontest)

[[10840   135]
 [ 1168   214]]

In [34]:
pd.DataFrame(confusiontest,columns=model.classes_,index=model.classes_)

        no  yes
no   10840  135
yes   1168  214

In [37]:
pd.DataFrame(confusiontrain,columns=model.classes_,index=model.classes_)

        no  yes
no   25201  372
yes   2729  529

In [38]:
print(classification_report(ytrain,ypredtrain))

             precision    recall  f1-score   support

         no       0.90      0.99      0.94     25573
        yes       0.59      0.16      0.25      3258

avg / total       0.87      0.89      0.86     28831

In [39]:
print(classification_report(ytest,ypredtest))

             precision    recall  f1-score   support

         no       0.90      0.99      0.94     10975
        yes       0.61      0.15      0.25      1382

avg / total       0.87      0.89      0.87     12357